/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_10 (
    input [3:0] alufn30,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      out[(i)*1+0-:1] = alufn30[({b[(i)*1+0-:1], a[(i)*1+0-:1]})*1+0-:1];
    end
  end
endmodule
